# Generated by Django 4.2.5 on 2023-11-03 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_category_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='color',
        ),
    ]
