# Generated by Django 4.2.5 on 2023-11-05 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
